project_id = "nlsaruzygpikvyviyrys"

[functions.search-places]
verify_jwt = false

[functions.geocode-location]
verify_jwt = false

[functions.autocomplete-places]
verify_jwt = false

[functions.generate-date-content]
verify_jwt = false