project_id = "nlsaruzygpikvyviyrys"

[functions.search-places]
verify_jwt = false

[functions.geocode-location]
verify_jwt = false

[functions.autocomplete-places]
verify_jwt = false

[functions.generate-date-content]
verify_jwt = false

[functions.filter-venues]
verify_jwt = false

[functions.get-weather]
verify_jwt = false

[functions.get-clothing-recommendation]
verify_jwt = false